services:
  - type: web
    name: konntek-bot
    env: python
    plan: free
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: STORAGE_PATH
        value: /opt/render/project/.render/storage/file_storage.json
    disks:
      - name: storage
        mountPath: /opt/render/project/.render/storage
        sizeGB: 50
