disks:
  - name: bot-data
    mountPath: /data
    sizeGB: 1

services:
  - type: web
    name: mytelegrambot
    env: python
    plan: starter
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: ton_token_telegram_ici
      - key: ADMIN_ID
        value: votre_id_telegram_ici
    disks:
      - bot-data
