services:
  - type: web
    name: konntek-bot
    runtime: python
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: votre_token_bot
      - key: ADMIN_ID
        value: votre_id_telegram
    disk:
      name: render-store
      mountPath: /opt/render/project/.render/storage
      sizeGB: 50
